### ISSUE TITLE
Get rid of hpack

### ISSUE THREAD

**Issue by david-christiansen** [gelisam/klister#111]
From my perspective, `hpack` is causing more problems than it solves.

With common stanzas, the repetetiveness of the cabal file format is much reduced, and I keep having to remember to run hpack when I'm building the project. It's also been causing some intermittent CI issues.

How do you all feel about replacing it with a `.cabal` file with a common stanza?

**Comment by gelisam** [comment]
sure, no objection

**Comment by langston-barrett** [comment]
Sounds fine!

**Comment by gelisam** [comment]
By the way, my colleague Deech wrote https://hackage.haskell.org/package/cabal-auto-expose, which brings some of the benefits of hpack to cabal files by automatically generating the list of .hs files, we could try using that if manually maintaining the list of files gets tiresome.

**Comment by david-christiansen** [comment]
I add/remove modules so infrequently that tweaking a line in a file is not a big deal. Hpack actually made this all more annoying for me, because I'd switch branches and forget to re-run it before building, and it'd complain :)
