### ISSUE TITLE
migrate away from Travis CI

### ISSUE THREAD

**Issue by gelisam** [gelisam/klister#121]
As [this reddit post](https://www.reddit.com/r/haskell/comments/jvbs49/psa_maintainers_should_think_about_migrating_off/) explains, Travis is dropping support for open-source projects, so we should consider switching to a different CI provider. The post recommends Github Actions, so that's what I plan to look at, but I'm open to other providers, e.g. Circle CI, if others have had a good experience with something.

**Comment by FranklinChen** [comment]
GitHub Actions works pretty well. I just started using https://github.com/kowainik/.github/blob/main/workflow-templates/ci.yml

**Comment by gelisam** [comment]
Fixed by #122. The kowanik template above didn't quite work, but it was a great starting point, thanks.

**Comment by langston-barrett** [comment]
Thanks for doing this @gelisam!
