### ISSUE TITLE
examples/io.kl fails on CI, but only for macOS

### ISSUE THREAD

**Issue by gelisam** [gelisam/klister#130]
The [error message](https://github.com/gelisam/klister/runs/1591279407#step:7:80) says

      Test output was different from 'examples/io.golden'. It was:
      #<output port> : Output-Port
      #<IO action> : (IO Integer)
      hello world!

which is weird because:

1. this is exactly the expected output
2. this is macOS, not Windows, so there shouldn't be any newline issues
3. I am running macOS on my laptop and that test passes for me

**Comment by david-christiansen** [comment]
Could it be a unicode normalization thing?

**Comment by gelisam** [comment]
Fixed by #131. Still no idea what the problem was.
