### ISSUE TITLE
what's the purpose of `ident`?

### ISSUE THREAD

**Issue by gelisam** [gelisam/klister#176]
`ident` is a builtin macro which is just like `quote`, except that it fails if its argument is anything other than an identifier.

```
(example (open-syntax (ident foo)))
-- =>
-- (identifier-contents "foo")

(example (open-syntax 'foo))
-- =>
-- (identifier-contents "foo")
```

There are no examples which use it. Can I delete it, or is it useful in a corner case which we haven't encountered yet?

**Comment by david-christiansen** [comment]
I think that it's just there for providing better errors for things like custom let or lambda forms, but I really don't remember for sure. Or perhaps for symmetry with the syntax pattern forms?

In any case, if we don't use it, then it's not really tested and should probably go.

**Comment by gelisam** [comment]
Removed by #177.
