### ISSUE TITLE
kind-inference bug with primitive type constructors

### ISSUE THREAD

**Issue by gelisam** [gelisam/klister#190]
Using `IO`, `List`, or `Maybe` at kind `* -> *` results in a kind error: 

```
#lang "prelude.kl"
(import "list.kl")

(datatype (OfUnit F)
  (of-unit
    (F Unit)))


-- of-unit-io : (OfUnit IO)
(define of-unit-io
  (of-unit (pure-IO unit)))

-- Kind mismatch at IO: * ≠ (* → *)
(example
  (the (OfUnit IO)
       of-unit-io))


-- of-unit-list : (OfUnit List)
(define of-unit-list
  (of-unit (list unit)))
(example of-unit-list)

-- Kind mismatch at List: * ≠ (* → *)
(example
  (the (OfUnit List)
       of-unit-list))


-- of-unit-maybe : (OfUnit Maybe)
(define of-unit-maybe
  (of-unit (just unit)))
(example of-unit-maybe)

-- Kind mismatch at Maybe: * ≠ (* → *)
(example
  (the (OfUnit (Maybe))
       of-unit-maybe))


-- works fine with non-primitive datatypes
(datatype (MyMaybe A)
  (my-nothing)
  (my-just A))

-- of-unit-my-maybe : (OfUnit (MyMaybe))
(define of-unit-my-maybe
  (of-unit (my-just unit)))
(example of-unit-my-maybe)

(example
  (the (OfUnit (MyMaybe))
       of-unit-my-maybe))
```

**Comment by gelisam** [comment]
The problem is that the IO macro expects its syntax to have the shape `(IO a)` for some `a`. When that assumption is true, the `(IO a)` type indeed has kind `*`. It just so happens that the IO macro provides the kind information before checking that assumption, so we get this confusing kind error instead of `expected a list with 2 entries, got IO`.

**Comment by gelisam** [comment]
One solution would be to fix the problem in the kernel, by changing the kernel's IO macro to allow the forms `IO`, `(IO)`, and `(IO a)`, and to provide the kind `* -> *` in the first two cases.

Another solution would be to fix the problem in the prelude, by creating a wrapper around IO and it's primitives:

```
(datatype (prelude.IO A)
  (prelude.io (kernel.IO A))

(define prelude.pure-IO
  (lambda (a)
    (prelude.io (kernel.pure-IO a))))

(define prelude.bind-IO
  (lambda (prelude.io-a cc)
    (prelude.io
      (case prelude.io-a
        [(prelude.io kernel.io-a)
         (kernel.bind-IO kernel.io-a
           (lambda (a)
             (case (cc a)
               [(prelude.io kernel.io-b)
                kernel.io-b])))]))))
```

**Comment by gelisam** [comment]
Unfortunately, `->` suffers from the same problem, and using the same trick with all lambdas and function applications seems really annoying.

Thus, I am leaning toward solving the problem in the kernel.

**Comment by david-christiansen** [comment]
Definitely solve it in the kernel! The current code path is from back
before we had higher-kinded polymorphism, and the rules are ML style when
they should really be Haskell-style.

fre. 30. dec. 2022 15.20 skrev Samuel Gélineau ***@***.***>:
