### ISSUE TITLE
Actually use #%module

### ISSUE THREAD

**Issue by david-christiansen** [gelisam/klister#40]
Right now, the system is ignoring #%module. This should be fixed by making the reader work more like Racket's in the presence of `#lang`.

**Comment by gelisam** [comment]
Could you please expand on the specific ways in which the reader needs to change in order to work more like Racket? `%#app` does work, does that mean that we currently desugar

```
(example (+ 2 2))
(example "bar")
```

into this:

```
(example (#%app + 2 2))
(example "bar")
```

instead of the following?

```
(#%module
  (example (#%app + (#%datum 2) (#%datum 2)))
  (example (#%datum "bar")))
```

**Comment by gelisam** [comment]
(we're missing `#%datum` too)
