### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by langston-barrett** [gelisam/klister#70]
It would be nice to have a string datatype! There are two ways I can see doing this:

 1. Introduce a `Char` datatype and have `String := List Char`, a la Haskell. This has all the same benefits and drawbacks as it did in Haskell, namely all the operations on such can already be defined in Klister, but the performance is horrible.
 2. Introduce a primitive `String` type and a few operations on it. What would be a good basis set? We could simply have cons and uncons, but that reduces this approach back to the above.

**Comment by langston-barrett** [comment]
This is a prerequisite for doing anything interesting with #32.

**Comment by david-christiansen** [comment]
Didn't #82 fix this?

**Comment by langston-barrett** [comment]
Yes!
